tap "oven-sh/bun"
tap "stripe/stripe-cli"

brew "asdf"
brew "azure-cli"
brew "bat"
brew "btop"
brew "chafa"
brew "chezmoi"
brew "coreutils"
brew "curl"
brew "eza"
brew "fd"
brew "fzf"
brew "gh"
brew "git"
brew "git-delta"
brew "glow"
brew "imagemagick"
brew "jq"
brew "lazygit"
brew "lua"
brew "luarocks"
brew "neovim"
brew "nginx"
brew "openapi-generator"
brew "postgresql@14", restart_service: :changed
brew "python@3.10"
brew "python@3.13"
brew "ripgrep"
brew "terminal-notifier"
brew "tree-sitter-cli"
brew "zrok"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
# Homebrew refuses to load formulae from non-official taps unless they are
# trusted; `trusted: true` records that here so `brew bundle` works unattended.
brew "oven-sh/bun/bun", trusted: true
brew "stripe/stripe-cli/stripe", trusted: true
brew "zoxide"

cask "1password-cli"
cask "font-jetbrains-mono"
cask "jordanbaird-ice"
cask "meetingbar"
cask "mitmproxy"
cask "ngrok"
cask "wezterm"
